# Generated by Django 4.1.3 on 2023-09-20 11:17

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.thumbnail_200_path),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.thumbnail_400_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_file',
            field=models.ImageField(upload_to=images.models.original_image_path),
        ),
    ]
