# Generated by Django 4.1.3 on 2023-09-21 08:31

from django.db import migrations, models
import django_advance_thumbnail.fields
import images.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_thumbnail_200_image_thumbnail_400_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_200',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(upload_to=images.models.thumbnail_200_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_400',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(upload_to=images.models.thumbnail_400_path),
        ),
    ]
